In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

df = pd.read_csv('Superstore_Orders_q1.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furni,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,NaN,41.9136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furni,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,NaN
2,3,CA-2016-138688,06/12/2016,06/16/2016,Second Class,DV-13045,United States,Los Angeles,California,90036,West,OFF-LA-10000240,OfficeSupply,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furni,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,NaN,OFF-ST-10000760,OfficeSupply,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12612,12613,CA-2016-272483,11/21/2015,11/23/2015,Standard Class,SB-20170,United States,Miami,Florida,33180,South,FUR-FU-10000732,Furni,Furnishings,Eldon 200 Class Desk Accessories,1257.3235,6,0.45,NaN
12613,12614,US-2017-668083,02/24/2014,03/01/2014,Standard Class,LC-16930,United States,Holland,Michigan,49423,Central,TEC-MA-10002178,Tech,Machines,Cisco CP-7937G Unified IP Conference Station P...,0.0100,4,0.32,NaN
12614,12615,US-2014-554326,05/29/2014,05/31/2014,Same Day,CC-12430,United States,Columbia,South Carolina,29203,South,OFF-AR-10004691,OfficeSupply,Art,Boston 1730 StandUp Electric Pencil Sharpener,815.0028,10,0.50,-34.0315
12615,12616,CA-2017-698123,05/04/2016,05/08/2016,Second Class,MS-17770,United States,Saint Charles,Missouri,63301,Central,FUR-CH-10001797,Furni,Chairs,"Safco Chair Connectors, 6/Carton",211.2283,5,0.45,-18.5582
12616,12617,US-2014-825903,07/16/2014,07/23/2014,Standard Class,AR-10405,United States,Lancaster,Pennsylvania,17602,East,OFF-BI-10002931,OfficeSupply,Binders,"Avery Trapezoid Extra Heavy Duty 4"" Binders",8.0706,6,0.80,-3.0401

In [3]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('-','_')
)
df

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furni,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,NaN,41.9136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furni,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,NaN
2,3,CA-2016-138688,06/12/2016,06/16/2016,Second Class,DV-13045,United States,Los Angeles,California,90036,West,OFF-LA-10000240,OfficeSupply,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furni,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,NaN,OFF-ST-10000760,OfficeSupply,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12612,12613,CA-2016-272483,11/21/2015,11/23/2015,Standard Class,SB-20170,United States,Miami,Florida,33180,South,FUR-FU-10000732,Furni,Furnishings,Eldon 200 Class Desk Accessories,1257.3235,6,0.45,NaN
12613,12614,US-2017-668083,02/24/2014,03/01/2014,Standard Class,LC-16930,United States,Holland,Michigan,49423,Central,TEC-MA-10002178,Tech,Machines,Cisco CP-7937G Unified IP Conference Station P...,0.0100,4,0.32,NaN
12614,12615,US-2014-554326,05/29/2014,05/31/2014,Same Day,CC-12430,United States,Columbia,South Carolina,29203,South,OFF-AR-10004691,OfficeSupply,Art,Boston 1730 StandUp Electric Pencil Sharpener,815.0028,10,0.50,-34.0315
12615,12616,CA-2017-698123,05/04/2016,05/08/2016,Second Class,MS-17770,United States,Saint Charles,Missouri,63301,Central,FUR-CH-10001797,Furni,Chairs,"Safco Chair Connectors, 6/Carton",211.2283,5,0.45,-18.5582
12616,12617,US-2014-825903,07/16/2014,07/23/2014,Standard Class,AR-10405,United States,Lancaster,Pennsylvania,17602,East,OFF-BI-10002931,OfficeSupply,Binders,"Avery Trapezoid Extra Heavy Duty 4"" Binders",8.0706,6,0.80,-3.0401

In [5]:
df['region'] = df['region'].replace('--', '')
df.head(15)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furni,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,NaN,41.9136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furni,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,NaN
2,3,CA-2016-138688,06/12/2016,06/16/2016,Second Class,DV-13045,United States,Los Angeles,California,90036,West,OFF-LA-10000240,OfficeSupply,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furni,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,NaN,OFF-ST-10000760,OfficeSupply,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,06/09/2014,06/14/2014,Standard Class,BH-11710,United States,Los Angeles,California,90032,West,FUR-FU-10001487,Furni,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,NaN
6,7,CA-2014-115812,06/09/2014,06/14/2014,Standard Class,BH-11710,United States,Los Angeles,California,90032,West,OFF-AR-10002833,OfficeSupply,Art,Newell 322,7.2800,4,0.00,1.97
7,8,CA-2014-115812,06/09/2014,06/14/2014,Standard Class,BH-11710,United States,Los Angeles,California,90032,West,TEC-PH-10002275,technologies,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,06/09/2014,06/14/2014,Standard Class,BH-11710,United States,Los Angeles,California,90032,West,OFF-BI-10003910,OfficeSupply,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,06/09/2014,06/14/2014,Standard Class,BH-11710,United States,Los Angeles,California,90032,West,OFF-AP-10002892,OfficeSupply,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.47
10,11,CA-2014-115812,06/09/2014,06/14/2014,Standard Class,BH-11710,United States,Los Angeles,California,90032,West,FUR-TA-10001539,Furni,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
11,12,CA-2014-115812,06/09/2014,06/14/2014,Standard Class,BH-11710,United States,Los Angeles,California,90032,West,TEC-PH-10002033,Tech,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,NaN
12,13,CA-2017-114412,04/15/2017,04/20/2017,Standard Class,AA-10480,United States,Concord,North Carolina,28027,,OFF-PA-10002365,OfficeSupply,Paper,Xerox 1967,15.5520,3,0.20,5.4432
13,14,CA-2016-161389,12/05/2016,12/10/2016,Standard Class,IM-15070,United States,Seattle,Washington,98103,West,OFF-BI-10003656,OfficeSupply,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922
14,15,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,United States,Fort Worth,Texas,76106,Central,OFF-AP-10002311,OfficeSupply,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.858

In [6]:
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12617 entries, 0 to 12616
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   row_id        12617 non-null  int64
 1   order_id      12617 non-null  object
 2   order_date    12617 non-null  object
 3   ship_date     12617 non-null  object
 4   ship_mode     12617 non-null  object
 5   customer_id   12617 non-null  object
 6   country       12617 non-null  object
 7   city          12617 non-null  object
 8   state         12617 non-null  object
 9   postal_code   12617 non-null  int64
 10  region        11979 non-null  object
 11  product_id    12617 non-null  object
 12  category      12617 non-null  object
 13  sub_category  12617 non-null  object
 14  product_name  12617 non-null  object
 15  sales         12617 non-null  float64
 16  quantity      12617 non-null  int64
 17  discount      11707 non-null  float64
 18  profit        11735 non-null  object
dtypes: float64(2), int64(3), object(14)
memory usage: 1.2+ MB

             row_id   postal_code         sales      quantity      discount
count  12617.000000  12617.000000  12617.000000  12617.000000  11707.000000
mean    6309.000000  55343.384719    276.477807      4.574780      0.201661
std     3642.358508  31559.152874    973.277767      3.109394      0.229770
min        1.000000   1040.000000      0.000000      1.000000      0.000000
25%     3155.000000  27604.000000     14.880000      2.000000      0.000000
50%     6309.000000  57103.000000     61.960000      4.000000      0.200000
75%     9463.000000  89115.000000    287.290800      6.000000      0.200000
max    12617.000000  99301.000000  39855.000000     14.000000      0.800000

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
row_id,12617.0,6309.000000,3642.358508,1.0,3155.00,6309.00,9463.0000,12617.0
postal_code,12617.0,55343.384719,31559.152874,1040.0,27604.00,57103.00,89115.0000,99301.0
sales,12617.0,276.477807,973.277767,0.0,14.88,61.96,287.2908,39855.0
quantity,12617.0,4.574780,3.109394,1.0,2.00,4.00,6.0000,14.0
discount,11707.0,0.201661,0.229770,0.0,0.00,0.20,0.2000,0.8

In [8]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])
df

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furni,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,NaN,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furni,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,NaN
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,United States,Los Angeles,California,90036,West,OFF-LA-10000240,OfficeSupply,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furni,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,United States,Fort Lauderdale,Florida,33311,NaN,OFF-ST-10000760,OfficeSupply,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12612,12613,CA-2016-272483,2015-11-21,2015-11-23,Standard Class,SB-20170,United States,Miami,Florida,33180,South,FUR-FU-10000732,Furni,Furnishings,Eldon 200 Class Desk Accessories,1257.3235,6,0.45,NaN
12613,12614,US-2017-668083,2014-02-24,2014-03-01,Standard Class,LC-16930,United States,Holland,Michigan,49423,Central,TEC-MA-10002178,Tech,Machines,Cisco CP-7937G Unified IP Conference Station P...,0.0100,4,0.32,NaN
12614,12615,US-2014-554326,2014-05-29,2014-05-31,Same Day,CC-12430,United States,Columbia,South Carolina,29203,South,OFF-AR-10004691,OfficeSupply,Art,Boston 1730 StandUp Electric Pencil Sharpener,815.0028,10,0.50,-34.0315
12615,12616,CA-2017-698123,2016-05-04,2016-05-08,Second Class,MS-17770,United States,Saint Charles,Missouri,63301,Central,FUR-CH-10001797,Furni,Chairs,"Safco Chair Connectors, 6/Carton",211.2283,5,0.45,-18.5582
12616,12617,US-2014-825903,2014-07-16,2014-07-23,Standard Class,AR-10405,United States,Lancaster,Pennsylvania,17602,East,OFF-BI-10002931,OfficeSupply,Binders,"Avery Trapezoid Extra Heavy Duty 4"" Binders",8.0706,6,0.80,-3.0401

In [10]:
df.isnull().sum()

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
country           0
city              0
state             0
postal_code       0
region          638
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount        910
profit          882
dtype: int64

In [12]:
df.to_csv('Superstore.csv', index=False)