In [18]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('messy_dirty_sales_data.csv')
df

,Order_ID,Product_Name,Order_Date,Price,Quantity,Discount_Code,Customer_Age
0,276,Apple iPhone 15s,12-09-2023,$-113,4,NaN,63.0
1,94,Apple Mac Book Air,12-05-2023,"$99,999",99999,SAVE20,22.0
2,7,Apple iPhone 15s,14-07-2023,"$-1,401",99999,SAVE20,60.0
3,168,Apple Mac Book Air,23-03-2023,-1979,99999,NaN,21.0
4,91,Apple iPhone 15s,17-04-2023,"$99,999",3,NaN,29.0
...,...,...,...,...,...,...,...
495,386,Apple iPhone 15,01-12-2023,"$1,301",99999,NaN,NaN
496,294,Apple iPhone 15s,10/14/2023,"₹1,271",7,SAVE20,35.0
497,414,Dell XPS 13,24-05-2023,"$99,999",4,OFFER5,NaN
498,492,Sony WH-1000XM5,02/23/2023,"₹99,999",7,SAVE20,19.0
499,344,Dell XPS 13,16-04-2023,"₹1,342",99999,DISC10,NaN

In [19]:
df = df.sort_values(by='Order_ID')
df

,Order_ID,Product_Name,Order_Date,Price,Quantity,Discount_Code,Customer_Age
72,1,Apple iPhone 15s,13-01-2023,$663,2,NaN,NaN
437,2,Apple Mac Book Air,08-05-2023,$161,9,NaN,30.0
58,3,Apple MacBook Air,08-03-2023,"$-1,306",99999,OFFER5,35.0
171,4,Samsung Galaxy S23,21-04-2023,$-289,99999,NaN,34.0
365,5,Apple iPhone 15,24-08-2023,"$-1,988",99999,NaN,41.0
...,...,...,...,...,...,...,...
452,496,Apple MacBook Air,24-02-2023,"₹-1,504",99999,NaN,46.0
287,497,Sony WH-1000XM5,22-07-2023,₹163,4,NEWUSER,52.0
112,498,Dell XPS 13,11/21/2023,"₹99,999",6,NaN,NaN
231,499,Apple MacBook Air,03/14/2023,"₹99,999",7,OFFER5,31.0
397,500,Dell XPS-13,19-04-2023,"$99,999",3,SAVE20,57.0

In [20]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed')
df

,Order_ID,Product_Name,Order_Date,Price,Quantity,Discount_Code,Customer_Age
72,1,Apple iPhone 15s,2023-01-13,$663,2,NaN,NaN
437,2,Apple Mac Book Air,2023-08-05,$161,9,NaN,30.0
58,3,Apple MacBook Air,2023-08-03,"$-1,306",99999,OFFER5,35.0
171,4,Samsung Galaxy S23,2023-04-21,$-289,99999,NaN,34.0
365,5,Apple iPhone 15,2023-08-24,"$-1,988",99999,NaN,41.0
...,...,...,...,...,...,...,...
452,496,Apple MacBook Air,2023-02-24,"₹-1,504",99999,NaN,46.0
287,497,Sony WH-1000XM5,2023-07-22,₹163,4,NEWUSER,52.0
112,498,Dell XPS 13,2023-11-21,"₹99,999",6,NaN,NaN
231,499,Apple MacBook Air,2023-03-14,"₹99,999",7,OFFER5,31.0
397,500,Dell XPS-13,2023-04-19,"$99,999",3,SAVE20,57.0

In [21]:
df['Price'] = df['Price'].str.replace('$', '').str.replace(',','').str.replace('₹','').str.replace(r'\D', '', regex=True).astype(float)
df

,Order_ID,Product_Name,Order_Date,Price,Quantity,Discount_Code,Customer_Age
72,1,Apple iPhone 15s,2023-01-13,663.0,2,NaN,NaN
437,2,Apple Mac Book Air,2023-08-05,161.0,9,NaN,30.0
58,3,Apple MacBook Air,2023-08-03,1306.0,99999,OFFER5,35.0
171,4,Samsung Galaxy S23,2023-04-21,289.0,99999,NaN,34.0
365,5,Apple iPhone 15,2023-08-24,1988.0,99999,NaN,41.0
...,...,...,...,...,...,...,...
452,496,Apple MacBook Air,2023-02-24,1504.0,99999,NaN,46.0
287,497,Sony WH-1000XM5,2023-07-22,163.0,4,NEWUSER,52.0
112,498,Dell XPS 13,2023-11-21,99999.0,6,NaN,NaN
231,499,Apple MacBook Air,2023-03-14,99999.0,7,OFFER5,31.0
397,500,Dell XPS-13,2023-04-19,99999.0,3,SAVE20,57.0

In [22]:
df.info()
df.shape
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 72 to 397
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       500 non-null    int64
 1   Product_Name   500 non-null    object
 2   Order_Date     500 non-null    datetime64[ns]
 3   Price          500 non-null    float64
 4   Quantity       500 non-null    int64
 5   Discount_Code  325 non-null    object
 6   Customer_Age   426 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 27.3+ KB

,Order_ID,Order_Date,Price,Quantity,Customer_Age
count,500.000000,500,500.000000,500.000000,426.000000
mean,251.852000,2023-06-28 17:45:36,35470.248000,53202.006000,43.384977
min,1.000000,2023-01-01 00:00:00,105.000000,1.000000,18.000000
25%,125.750000,2023-03-25 06:00:00,759.750000,6.000000,32.000000
50%,252.500000,2023-06-28 12:00:00,1504.500000,99999.000000,44.000000
75%,378.250000,2023-09-30 00:00:00,99999.000000,99999.000000,56.000000
max,500.000000,2024-01-01 00:00:00,99999.000000,99999.000000,65.000000
std,145.236626,NaN,47192.447014,49944.259268,14.003097

In [23]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Order_ID,500.0,251.852,1.0,125.75,252.5,378.25,500.0,145.236626
Order_Date,500,2023-06-28 17:45:36,2023-01-01 00:00:00,2023-03-25 06:00:00,2023-06-28 12:00:00,2023-09-30 00:00:00,2024-01-01 00:00:00,NaN
Price,500.0,35470.248,105.0,759.75,1504.5,99999.0,99999.0,47192.447014
Quantity,500.0,53202.006,1.0,6.0,99999.0,99999.0,99999.0,49944.259268
Customer_Age,426.0,43.384977,18.0,32.0,44.0,56.0,65.0,14.003097

In [24]:
df.replace(99999, np.nan, inplace=True)
df

,Order_ID,Product_Name,Order_Date,Price,Quantity,Discount_Code,Customer_Age
72,1,Apple iPhone 15s,2023-01-13,663.0,2.0,NaN,NaN
437,2,Apple Mac Book Air,2023-08-05,161.0,9.0,NaN,30.0
58,3,Apple MacBook Air,2023-08-03,1306.0,NaN,OFFER5,35.0
171,4,Samsung Galaxy S23,2023-04-21,289.0,NaN,NaN,34.0
365,5,Apple iPhone 15,2023-08-24,1988.0,NaN,NaN,41.0
...,...,...,...,...,...,...,...
452,496,Apple MacBook Air,2023-02-24,1504.0,NaN,NaN,46.0
287,497,Sony WH-1000XM5,2023-07-22,163.0,4.0,NEWUSER,52.0
112,498,Dell XPS 13,2023-11-21,NaN,6.0,NaN,NaN
231,499,Apple MacBook Air,2023-03-14,NaN,7.0,OFFER5,31.0
397,500,Dell XPS-13,2023-04-19,NaN,3.0,SAVE20,57.0

In [25]:
df.isnull().sum()

Order_ID           0
Product_Name       0
Order_Date         0
Price            174
Quantity         266
Discount_Code    175
Customer_Age      74
dtype: int64

In [26]:
df['Discount_Code'] = df['Discount_Code'].fillna('NA')
df.isnull().sum()

Order_ID           0
Product_Name       0
Order_Date         0
Price            174
Quantity         266
Discount_Code      0
Customer_Age      74
dtype: int64

In [27]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Price'] = df['Price'].fillna(df['Price'].median())
df['Customer_Age'] = df['Customer_Age'].fillna(df['Customer_Age'].median())
df.isnull().sum()

Order_ID         0
Product_Name     0
Order_Date       0
Price            0
Quantity         0
Discount_Code    0
Customer_Age     0
dtype: int64

In [28]:
print("Duplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
20

In [29]:
df.drop_duplicates(inplace=True)
print("Duplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
0

In [30]:
df.to_csv('cleaned_sales.csv', index=False)